# Generated by Django 4.1.5 on 2023-03-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecommendationSystem_App', '0002_category_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(upload_to='uploads/')),
                ('price', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
