# Generated by Django 4.1.5 on 2023-03-10 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecommendationSystem_App', '0003_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
