# Generated by Django 4.1.5 on 2023-03-10 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecommendationSystem_App', '0004_rename_products_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
