# Generated by Django 4.1.5 on 2023-03-13 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecommendationSystem_App', '0006_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
    ]
