# Generated by Django 4.1.5 on 2023-03-13 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecommendationSystem_App', '0007_remove_product_poster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='poster',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product_Category', to='RecommendationSystem_App.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
