# Generated by Django 4.1.5 on 2023-03-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecommendationSystem_App', '0008_product_poster_product_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='poster',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
